name: 'test1'

on:
  workflow_dispatch:
  push:
    branches:
     - main
  schedule:
    - cron: '15 */12 * * *'



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Test
      env:
        CPAUTH: ${{secrets.CPAUTH}}
      run: |
        sudo docker run -d -p 8080:8080 --name go-proxy-bingai --restart=unless-stopped adams549659584/go-proxy-bingai
        echo "curl -L https://cpolar.com/download/cpolar.sh | bash && cpolar -authtoken $CPAUTH -local_port 8080" > cp.sh
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
